### ISSUE TITLE
v1.0 does not include #2

### ISSUE THREAD

**Issue by elad-eyal** [colbyhill21/angular-full-ci#3]
When I try to use this
```
 - name: Angular Full CI
   uses: colbyhill21/angular-full-ci/@v1.0
   with:
     working_directory: ./something/something
     testcommand: run test:ci
```

I get
```
Warning: Unexpected input(s) 'working_directory', valid inputs are ['entryPoint', 'args', 'testcommand', 'mocha']
```

I think the PR from #2 did not make it into `v1.0`
